/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 21PROGA005
 */
public class autores extends javax.swing.JFrame {

    /**
     * Creates new form autores
     */
    public autores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pancolorcito = new javax.swing.JPanel();
        lblaut = new javax.swing.JLabel();
        lbln = new javax.swing.JLabel();
        lblprogra = new javax.swing.JLabel();
        lblmatricula = new javax.swing.JLabel();
        lbl3a = new javax.swing.JLabel();
        lblintit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pancolorcito.setBackground(new java.awt.Color(204, 204, 255));

        lblaut.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblaut.setText("AUTORES ");

        lbln.setText("Elian Guadalupe Negra Aguilar");

        lblprogra.setText("Programacion");

        lblmatricula.setText("Matricula: 213616050940280");

        lbl3a.setText("3'A'");

        lblintit.setText("Institucion: Cbtis94");

        javax.swing.GroupLayout pancolorcitoLayout = new javax.swing.GroupLayout(pancolorcito);
        pancolorcito.setLayout(pancolorcitoLayout);
        pancolorcitoLayout.setHorizontalGroup(
            pancolorcitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pancolorcitoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblaut)
                .addGap(56, 56, 56))
            .addGroup(pancolorcitoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pancolorcitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbln)
                    .addGroup(pancolorcitoLayout.createSequentialGroup()
                        .addComponent(lblprogra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl3a))
                    .addComponent(lblmatricula)
                    .addComponent(lblintit))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pancolorcitoLayout.setVerticalGroup(
            pancolorcitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pancolorcitoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblaut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbln)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pancolorcitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprogra)
                    .addComponent(lbl3a))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblmatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblintit)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pancolorcito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pancolorcito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(autores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(autores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(autores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(autores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new autores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl3a;
    private javax.swing.JLabel lblaut;
    private javax.swing.JLabel lblintit;
    private javax.swing.JLabel lblmatricula;
    private javax.swing.JLabel lbln;
    private javax.swing.JLabel lblprogra;
    private javax.swing.JPanel pancolorcito;
    // End of variables declaration//GEN-END:variables
}
