/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 21PROGA005
 */
public class ventana5 extends javax.swing.JFrame {

    /**
     * Creates new form ventana5
     */
    
    public ventana5() {
        initComponents();
    }
alumno objeto = new alumno();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitulillo = new javax.swing.JLabel();
        txtnombre1 = new javax.swing.JTextField();
        txtespec2 = new javax.swing.JTextField();
        txtmateria3 = new javax.swing.JTextField();
        txtcosto = new javax.swing.JTextField();
        txt0 = new javax.swing.JTextField();
        btbcer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitulillo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbltitulillo.setText("FICHA PARA EXAMEN EXTRAORDINARIO");

        txtnombre1.setBackground(new java.awt.Color(204, 255, 204));
        txtnombre1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtnombre1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtespec2.setBackground(new java.awt.Color(204, 255, 204));
        txtespec2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtespec2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtmateria3.setBackground(new java.awt.Color(204, 255, 204));
        txtmateria3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtmateria3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtcosto.setBackground(new java.awt.Color(204, 255, 204));
        txtcosto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtcosto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcosto.setText("costo  $50");

        txt0.setBackground(new java.awt.Color(204, 255, 204));
        txt0.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt0.setText("Presentarce el dia 16 de Diciembre a las 13:00 horas,  salon D-4");

        btbcer.setBackground(new java.awt.Color(0, 153, 153));
        btbcer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btbcer.setText("CERRAR");
        btbcer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbcerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbltitulillo)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btbcer)
                        .addGap(14, 14, 14))))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcosto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmateria3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtespec2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt0, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbltitulillo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtespec2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(txtmateria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btbcer)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbcerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbcerActionPerformed
       autores k = new autores();
  k.setVisible(true);
  this.setVisible(false);
  
  
 
    }//GEN-LAST:event_btbcerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbcer;
    private javax.swing.JLabel lbltitulillo;
    private javax.swing.JTextField txt0;
    private javax.swing.JTextField txtcosto;
    private javax.swing.JTextField txtespec2;
    private javax.swing.JTextField txtmateria3;
    private javax.swing.JTextField txtnombre1;
    // End of variables declaration//GEN-END:variables
}
